img_size: [120,160]
top_cutoff: 40

colors:
  YELLOW:
    low: [25,140,100]
    high: [45,255,255]

duckie_detector_parameters:
  canny_thresholds: [80,200]
  canny_aperture_size: 3
  dilation_kernel_size: 3
  hough_threshold: 2
  hough_min_line_length: 3
  hough_max_line_gap: 1